### ISSUE TITLE
路径不对

### ISSUE THREAD

**Issue by zxzxzxygithub** [asiontang/XposedNoRebootModuleSample#1]
可能是手机不一样，我的改成下面这个apk路径就ok了
        final String packageName = "com.test.emptydemo";
        String filePath = String.format("/data/app/%s-%d/base.apk", packageName, 1);
        if (!new File(filePath).exists()) {
            filePath = String.format("/data/app/%s-%d/base.apk", packageName, 2);
            if (!new File(filePath).exists()) {
                XposedBridge.log("Error:在/data/app找不到APK文件" + packageName);
                return;
            }
        }

**Comment by asiontang** [comment]
使用新版本的方式兼容性更好,支持Android 9.0以上的随机路径.
