### ISSUE TITLE
貌似没有生效还是要重启手机

### ISSUE THREAD

**Issue by zxzxzxygithub** [asiontang/XposedNoRebootModuleSample#2]
貌似没有生效还是要重启手机

**Comment by zxzxzxygithub** [comment]
hook自身apk的话倒是不用重启，但是hook别人的apk的话还是要重启的

**Comment by asiontang** [comment]
姿势不对.参考实际可用的项目[asiontang/78.Xposed](https://github.com/asiontang/78.Xposed)
